# ism="Otabek"
# yosh=15
# print(ism)
# print(yosh)

# ism="Otabek"
# print(ism)
# ism="Otabek"
# print(ism)

# print("men yangi ☎ oldim")
#
# ism="Otabek"
# print("Mening ismim " + ism)

# ism="Otabek "
# familiya="Rozmetov"
# print(ism + familiya)

# ism="Otabek"
# familiya= "Ro'zmetov"
# ism_sharif=f"{ism} {familiya}"
# print(ism_sharif)

# ism="Otabek"
# familiya="Ro'zmetov"
# print(f"Salom, mening ismim {ism} {familiya}!")

# print('Hello World!')
# print('Hello \tWorld!')
# print('Hello \nWorld!')

# ism="Otabek"
# familiya="Ro'zmetov"
# ism_sharif=f"{ism} {familiya}"
# print(ism_sharif.lower())

# ism_sharif="otabek ro'zmetov"
# print(ism_sharif.title())
#
# ism_sharif="otabek ro'zmetov"
# print(ism_sharif.capitalize())

# meva="   olma   "
# print("Men " + meva.lstrip() + "yaxshi ko'raman")
# print("Men " + meva.rstrip() + " yaxshi ko'raman")
# print("Men " + meva.strip()  + " yaxshi ko'raman")
# print("Men " + meva +"yaxshi ko'raman")
#
# ism=input("Ismingiz nima?")
# print("Asalomu alykum, " + ism)


# 1.
# bmw="Hello World"
# print(bmw)
# 2.
# xabar="Samsung " + "Bmw"
# print(xabar)
# 3.
# klas="Samsung"
# print(klas)
# 4.
# ism=input("Ismingiz niam? ")
# print("Asalomu alykum, " +ism.title())
#
# ism = input("ismingiz nima? ")
# print("Asalomu alykum, " +ism.title())

ism= input("Ismingiz nima? ")
print("asalomu alaykum, " +ism.title())